import { ConstantExperience } from '../interfaces/experience'

export const EXPERIENCE = {
    freelancer: {
        title: 'FreeLancer',
        subTitle: 'Fullstack Developer',
        startDate: '3/2021',
        endDate: '6/2022',
        projects: [
            {
                title: 'LiveCV',
                overview:
                    'A system with 4 actors: Admin, Expert, Candidate, and Staff. Provides main functionality to build CVs and use that CV for practice interviews in the Job that the user needs.',
                role: 'Leader, Mobile Developer',
                technologies: [
                    'Flutter',
                    'GetX',
                    'Agora',
                    'Firebase',
                    'Momo/Paypal API',
                    'Nginx',
                    'Github CI/CD',
                    'NextJS',
                    'TailwindCSS',
                    'React Query',
                    'NestJS',
                    'PostgreSQL',
                    'Docker',
                    'Digital Ocean',
                    'AWS S3 Service',
                ],
                startDate: '03/2022',
                endDate: '12/2023',
            },
            {
                title: 'FuQuiz',
                overview:
                    'An online quiz practice webstore with the following features: purchase courses, quiz practice, view blog, manage a system for 5 different roles ( sale, marketing, customer, admin, expert ),...',
                role: 'Fontend Developer',
                technologies: [
                    'NextJS',
                    'TailwindCSS',
                    'Redux',
                    'NestJS',
                    'TypeORM',
                    'MYSQL2',
                    'Docker',
                    'Github CI/CD',
                    'Digital Ocean',
                ],
                startDate: '05/2022',
                endDate: '08/2022',
            },
            {
                title: 'Dating App',
                overview:
                    'An online dating app based on Tinder with matching and chatting as its main functions.',
                role: 'Full-Stack Developer',
                technologies: [
                    'ReactJS',
                    'Redux',
                    'TailwindCSS',
                    'NestJS',
                    'TypeORM',
                    'MYSQL2',
                    'Docker',
                    'Github CI/CD',
                    'Digital Ocean',
                ],
                startDate: '12/2021',
                endDate: '03/2022',
            },
            {
                title: 'Clothes Shop',
                overview:
                    'An online web store to sell clothes with the following main features: cart, purchase order, analyst system, and manage product,...',
                role: 'Full-Stack Developer',
                technologies: [
                    'ReactJS',
                    'Redux',
                    'TailwindCSS',
                    'ExpressJS',
                    'TypeORM',
                    'MYSQL2',
                    'Docker',
                    'Github CI/CD',
                    'Digital Ocean',
                ],
                startDate: '09/2021',
                endDate: '11/2021',
            },
            {
                title: 'Joy-message',
                overview:
                    'A package of Joi to generate more friendly messages base on Joy packages.',
                role: 'Full-Stack Developer',
                technologies: ['TypeScript', 'Joi'],
                startDate: '05/2021',
                endDate: '06/2021',
            },
        ],
    },
    tpp: {
        title: 'TP&P Technology',
        subTitle: 'Junior Developer',
        startDate: '06/2022',
        endDate: 'Now',
        company: 'TP&P Technology',
        projects: [
            {
                title: 'Klikdokter',
                link: 'https://klikdokter.com',
                overview:
                    "Klikdokter is Indonesia's leading health-tech company. Provide accurate medical information fromtrusted doctors and we help connect you with the right clinic or doctor.",
                role: 'Frontend Developer',
                startDate: '8/2022',
                endDate: '10/2022',
                technologies: ['NextJS', 'Docker', 'Nginx', 'Microservice'],
            },
            {
                title: 'PAF',
                link: '',
                overview:
                    'A financial web & mobile application about shows analytics data from Intrinio API. The Project includes about 8 different services with microservices, SSO features',
                role: 'Frontend Developer',
                subTitle: 'Park Avenue Financial',
                startDate: '10/2022',
                endDate: '8/2023',
                technologies: [
                    'ReactJS (ViteJS)',
                    'TailwindCSS',
                    'Charkra UI',
                    'MUI',
                    'React Router',
                    'React Query',
                    'Nginx',
                    'Docker',
                    'Azure Services',
                    'FastAPI',
                ],
            },
            {
                title: 'Nissan',
                overview:
                    "A project from Nissan. Building a system for communication between Car agents through UI on the car's screen and web UI.",
                role: 'Frontend Developer',
                subTitle: 'Nissan',
                startDate: '4/2023',
                endDate: '7/2023',
                technologies: ['ReactJS', 'ElectronJS', 'NestJS', 'Docker', 'Nginx'],
            },
            {
                title: 'FSS',
                overview:
                    'A CMS system for managing workflow and controlling the progress of the work of technicians on each site visit.',
                role: 'Frontend Developer',
                subTitle: 'Federated System Service',
                startDate: '8/2023',
                endDate: '11/2023',
                technologies: [
                    'Lerna',
                    'NextJS',
                    'React Native',
                    'Antd',
                    'React Hook Form',
                    'React Query',
                    'TypeScript',
                    'Azure ADB2C',
                    'Azure blob storage',
                    'AKS',
                    'HubSpot API',
                    'Docker',
                    'Kong Gateway',
                    'Microservices',
                    'FastAPI',
                    'Alembic',
                ],
            },
            {
                title: 'ULC',
                overview:
                    'A lotto app for users to register and buy lotto. The target is cover all possible combination numbers and take the jackpot of the Powerball Lotto in the United States.',
                role: 'Mobile Developer',
                subTitle: 'Ultimate Lotto Club',
                startDate: '11/2023',
                endDate: 'now',
                technologies: [
                    'Flutter',
                    'GetX',
                    'OpenCV',
                    'Retrofit',
                    'Dio',
                    'AWS',
                    'Docker',
                    'FastAPI',
                ],
            },
        ],
    },
} satisfies ConstantExperience
